# Generated by Django 2.1.8 on 2019-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
